{
 "title": "[TKS] Kubernetes / View / Cluster Global",
 "description": "This is a 'Global View' dashboard for your Kubernetes cluster(s). Made for prometheus and take advantage of the latest Grafana features. Originaed from GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "tks"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "taco_cluster", "label": "Cluster", "query": { "query": "label_values(up, taco_cluster)" } },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Overview ($taco_cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{taco_cluster=\"$taco_cluster\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{taco_cluster=\"$taco_cluster\",unit=\"core\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{taco_cluster=\"$taco_cluster\",unit=\"core\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{taco_cluster=\"$taco_cluster\"} - node_memory_MemAvailable_bytes{taco_cluster=\"$taco_cluster\"}) / sum(node_memory_MemTotal_bytes{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{taco_cluster=\"$taco_cluster\",unit=\"byte\"}) / sum(machine_memory_bytes{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{taco_cluster=\"$taco_cluster\",unit=\"byte\"}) / sum(machine_memory_bytes{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_pod_container_status_running{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{taco_cluster=\"$taco_cluster\",phase='Running'})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_endpoint_info{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(kube_ingress_info{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(up{taco_cluster=\"$taco_cluster\",job=\"node-exporter\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{taco_cluster=\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{taco_cluster=\"$taco_cluster\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{taco_cluster=\"$taco_cluster\",unit=\"core\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{taco_cluster=\"$taco_cluster\",unit=\"core\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_cpu_cores{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{taco_cluster=\"$taco_cluster\"} - node_memory_MemAvailable_bytes{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{taco_cluster=\"$taco_cluster\",unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{taco_cluster=\"$taco_cluster\",unit=\"byte\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_memory_bytes{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{taco_cluster=\"$taco_cluster\",phase='Running'})"
    }
   ]
  },
  {
   "title": "Node Readiness (1: Ready)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=\"$taco_cluster\",status=\"true\",condition=\"Ready\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "description": "Number of Nodes Unavailable",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{taco_cluster=\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Nodes Status",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=\"$taco_cluster\",condition=\"Ready\", status!=\"true\"})",
     "legendFormat": "NotReady"
    },
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=\"$taco_cluster\",condition=\"DiskPressure\", status=\"true\"})",
     "legendFormat": "DiskPressure"
    },
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=\"$taco_cluster\",condition=\"MemoryPressure\", status=\"true\"})",
     "legendFormat": "MemoryPressure"
    },
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=\"$taco_cluster\",condition=\"PIDPressure\", status=\"true\"})",
     "legendFormat": "PIDPressure"
    },
    {
     "expr": "sum(kube_node_status_condition{taco_cluster=\"$taco_cluster\",condition=\"NetworkUnavailable\", status=\"true\"})",
     "legendFormat": "NetworkUnavailable"
    }
   ]
  },
  {
   "title": "Containers Restarts (60 Min)",
   "type": "stat",
   "description": "Numbers of containers of cluster that restarts in the last 60 minutes",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{taco_cluster=\"$taco_cluster\",namespace!=\"kube-system\"}[60m]))"
    }
   ]
  },
  { "title": "Resources ($taco_cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{taco_cluster=\"$taco_cluster\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "CPU usage in %"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{taco_cluster=\"$taco_cluster\"} - node_memory_MemAvailable_bytes{taco_cluster=\"$taco_cluster\"}) / sum(node_memory_MemTotal_bytes{taco_cluster=\"$taco_cluster\"})",
     "legendFormat": "Memory usage in %"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{taco_cluster=\"$taco_cluster\",image!=\"\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{taco_cluster=\"$taco_cluster\",image!=\"\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{taco_cluster=\"$taco_cluster\",mode=\"idle\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{taco_cluster=\"$taco_cluster\"} - node_memory_MemAvailable_bytes{taco_cluster=\"$taco_cluster\"}) by (instance)",
     "legendFormat": "{{ node}}"
    }
   ]
  },
  { "title": "Network ($taco_cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Global Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{taco_cluster=\"$taco_cluster\"}[$__rate_interval]))",
     "legendFormat": "Total received bytes"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{taco_cluster=\"$taco_cluster\"}[$__rate_interval]))",
     "legendFormat": "Total transmitted bytes"
    }
   ]
  },
  {
   "title": "Network Saturation - Packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{taco_cluster=\"$taco_cluster\"}[$__rate_interval]))",
     "legendFormat": "Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{taco_cluster=\"$taco_cluster\"}[$__rate_interval]))",
     "legendFormat": "Packets dropped (transmit)"
    }
   ]
  },
  {
   "title": "Network Received by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{taco_cluster=\"$taco_cluster\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "Received bytes in {{ namespace }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{taco_cluster=\"$taco_cluster\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "Transmitted bytes in {{ namespace }}"
    }
   ]
  },
  {
   "title": "Network Received by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{taco_cluster=\"$taco_cluster\"}[$__rate_interval])) by (node)",
     "legendFormat": "Received bytes in {{ node }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{taco_cluster=\"$taco_cluster\"}[$__rate_interval])) by (node)",
     "legendFormat": "Transmitted bytes in {{ node }}"
    }
   ]
  },
  {
   "title": "Storage - PV usage ($taco_cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 }
  },
  {
   "title": "PV Usage (%) ",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes{taco_cluster=\"$taco_cluster\"} / kubelet_volume_stats_capacity_bytes{taco_cluster=\"$taco_cluster\"}) * 100 ",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}